#!/bin/sh

NAME='minutos'
DJANGODIR=/webapps/minutos/minutos_env/minutos
SOCKFILE=/webapps/minutos/minutos_env/run/gunicorn.sock
USER=minutos
GROUP=webapps
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=minutos.settingsprod
DJANGO_WSGI_MODULE=minutos.wsgi
TIMEOUT=120

cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
